import type { CSSProperties } from "react";

export const s = {
  overlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,.32)",
    zIndex: 40,
  } as CSSProperties,
  drawer: {
    position: "fixed",
    right: 0,
    top: 0,
    bottom: 0,
    width: 480,
    maxWidth: "100vw",
    background: "var(--bg-surface)",
    borderLeft: "1px solid var(--border)",
    display: "flex",
    flexDirection: "column",
    zIndex: 41,
  } as CSSProperties,
  header: {
    padding: "16px 20px",
    borderBottom: "1px solid var(--border)",
    display: "flex",
    alignItems: "flex-start",
    gap: 12,
  } as CSSProperties,
  titleCol: { flex: 1, display: "flex", flexDirection: "column", gap: 4 } as CSSProperties,
  title: { fontSize: 14, fontWeight: 600, color: "var(--text-primary)" } as CSSProperties,
  subtitle: { fontSize: 12, color: "var(--text-muted)" } as CSSProperties,
  searchWrap: {
    padding: "12px 20px",
    borderBottom: "1px solid var(--border)",
  } as CSSProperties,
  search: {
    width: "100%",
    height: 32,
    padding: "0 10px",
    background: "var(--bg-input)",
    border: "1px solid var(--border)",
    borderRadius: 6,
    color: "var(--text-primary)",
    fontSize: 13,
  } as CSSProperties,
  list: {
    flex: 1,
    overflow: "auto",
    padding: "8px 12px",
    display: "flex",
    flexDirection: "column",
    gap: 6,
  } as CSSProperties,
  empty: {
    padding: "24px 12px",
    textAlign: "center",
    color: "var(--text-muted)",
    fontSize: 13,
  } as CSSProperties,
  row: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "10px 12px",
    background: "transparent",
    border: "1px solid var(--border)",
    borderRadius: 6,
    cursor: "pointer",
    textAlign: "left",
    color: "var(--text-primary)",
  } as CSSProperties,
  rowName: { flex: 1, fontFamily: "var(--mono)", fontSize: 13 } as CSSProperties,
};
