import type { CSSProperties } from "react";

export const s = {
  card: {
    display: "flex",
    flexDirection: "column",
    gap: 14,
    padding: 16,
    border: "1px solid var(--border, #e5e7eb)",
    borderLeft: "4px solid var(--accent-intent, #8b5cf6)",
    background: "var(--accent-intent-bg, rgba(139, 92, 246, 0.06))",
    borderRadius: 8,
  } satisfies CSSProperties,
  refreshingBanner: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "6px 10px",
    borderRadius: 6,
    background: "var(--accent-intent-bg, rgba(139, 92, 246, 0.12))",
    border: "1px solid var(--accent-intent, #8b5cf6)",
    color: "var(--accent-intent, #8b5cf6)",
    fontSize: 12,
  } satisfies CSSProperties,
  goal: {
    fontSize: 14,
    lineHeight: 1.5,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  scopeGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 16,
  } satisfies CSSProperties,
  scopeColumnLabel: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    marginBottom: 6,
  } satisfies CSSProperties,
  scopeList: {
    margin: 0,
    paddingLeft: 18,
    fontSize: 13,
    color: "var(--text-secondary)",
    lineHeight: 1.6,
  } satisfies CSSProperties,
  riskRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
  } satisfies CSSProperties,
  riskChip: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: "3px 9px",
    borderRadius: 999,
    background: "var(--bg-elevated)",
    border: "1px solid var(--border)",
    fontSize: 12,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  referenceRow: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 8,
  } satisfies CSSProperties,
  referenceLabel: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  referenceChip: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    padding: "3px 9px",
    borderRadius: 999,
    background: "var(--bg-elevated)",
    border: "1px solid var(--border)",
    fontSize: 12,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  footer: {
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  staleBanner: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    padding: "8px 12px",
    borderRadius: 6,
    background: "var(--warn-bg, #3a2a05)",
    border: "1px solid var(--warn, #d97706)",
    color: "var(--warn, #d97706)",
    fontSize: 13,
  } satisfies CSSProperties,
  progressLine: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 13,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  errorText: {
    fontSize: 13,
    color: "var(--crit, #dc2626)",
  } satisfies CSSProperties,
} as const;
