import type { CSSProperties } from "react";

export const s = {
  picker: {
    display: "flex",
    flexDirection: "column",
    gap: 12,
    padding: "24px 0",
    alignItems: "stretch",
  } as CSSProperties,
  hiddenInput: {
    position: "absolute",
    inset: 0,
    opacity: 0,
    cursor: "pointer",
  } as CSSProperties,
  pickerBox: {
    position: "relative",
    border: "2px dashed var(--border)",
    borderRadius: 12,
    padding: "32px 16px",
    textAlign: "center",
    cursor: "pointer",
    color: "var(--muted-foreground)",
  } as CSSProperties,
  hint: { fontSize: 12, color: "var(--muted-foreground)" } as CSSProperties,
  previewGrid: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) minmax(0, 1fr)",
    gap: 16,
  } as CSSProperties,
  field: { display: "flex", flexDirection: "column", gap: 6, marginBottom: 12 } as CSSProperties,
  label: { fontSize: 12, fontWeight: 600 } as CSSProperties,
  input: {
    padding: "8px 10px",
    border: "1px solid var(--border)",
    borderRadius: 6,
    fontSize: 14,
    background: "var(--bg)",
    color: "var(--fg)",
  } as CSSProperties,
  bodyPreview: {
    maxHeight: 360,
    overflow: "auto",
    border: "1px solid var(--border)",
    borderRadius: 8,
    padding: 12,
  } as CSSProperties,
  warningsRow: { display: "flex", flexWrap: "wrap", gap: 6, marginBottom: 12 } as CSSProperties,
  warningChip: {
    background: "color-mix(in srgb, var(--warn) 18%, transparent)",
    color: "var(--warn)",
    fontSize: 12,
    borderRadius: 999,
    padding: "2px 10px",
  } as CSSProperties,
  errorBox: {
    background: "color-mix(in srgb, var(--danger) 12%, transparent)",
    color: "var(--danger)",
    borderRadius: 8,
    padding: "10px 12px",
    fontSize: 13,
    marginBottom: 12,
  } as CSSProperties,
  trustBox: {
    background: "color-mix(in srgb, var(--warn) 18%, transparent)",
    border: "1px solid color-mix(in srgb, var(--warn) 40%, transparent)",
    borderRadius: 10,
    padding: "10px 12px",
    fontSize: 13,
    marginBottom: 12,
    display: "flex",
    gap: 8,
    alignItems: "flex-start",
  } as CSSProperties,
  footer: { display: "flex", justifyContent: "flex-end", gap: 8 } as CSSProperties,
};
