import type { CSSProperties } from "react";

/** Co-located styles for VersionsTab + VersionRow. */
export const s = {
  wrap: { maxWidth: 760 } satisfies CSSProperties,
  header: { display: "flex", alignItems: "center", gap: 10, marginBottom: 16 } satisfies CSSProperties,
  title: { fontSize: 18, fontWeight: 700 } satisfies CSSProperties,
  loadError: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    padding: 12,
    fontSize: 13,
    color: "var(--danger)",
    display: "flex",
    gap: 10,
    alignItems: "center",
  } satisfies CSSProperties,
  onlyOne: {
    border: "1px dashed var(--border)",
    borderRadius: 8,
    padding: 16,
    color: "var(--text-secondary)",
    fontSize: 13,
  } satisfies CSSProperties,
  list: { display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  row: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-surface)",
    overflow: "hidden",
  } satisfies CSSProperties,
  rowHeader: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "10px 14px",
    cursor: "pointer",
    background: "transparent",
    border: 0,
    width: "100%",
    textAlign: "left" as const,
    color: "inherit",
    font: "inherit",
  } satisfies CSSProperties,
  versionLabel: {
    fontFamily: "var(--font-mono)",
    fontSize: 13,
    fontWeight: 600,
  } satisfies CSSProperties,
  timestamp: { fontSize: 13, color: "var(--text-secondary)" } satisfies CSSProperties,
  chevron: { marginLeft: "auto", color: "var(--text-secondary)" } satisfies CSSProperties,
  rowBody: {
    padding: "12px 14px 16px",
    borderTop: "1px solid var(--border)",
    display: "flex",
    flexDirection: "column",
    gap: 10,
  } satisfies CSSProperties,
  defList: {
    display: "grid",
    gridTemplateColumns: "140px 1fr",
    rowGap: 6,
    columnGap: 12,
    fontSize: 13,
  } satisfies CSSProperties,
  defKey: { color: "var(--text-secondary)" } satisfies CSSProperties,
  defVal: { color: "var(--text-primary)" } satisfies CSSProperties,
  promptBlock: {
    fontFamily: "var(--font-mono)",
    fontSize: 12,
    whiteSpace: "pre-wrap" as const,
    background: "var(--bg-elev)",
    border: "1px solid var(--border)",
    borderRadius: 6,
    padding: 10,
    maxHeight: 280,
    overflow: "auto",
  } satisfies CSSProperties,
  skillDeleted: { color: "var(--text-muted)", marginLeft: 4 } satisfies CSSProperties,
} as const;
