import type { CSSProperties } from "react";

export const s = {
  wrap: { display: "flex", flexDirection: "column", gap: 14 } as CSSProperties,
  header: { display: "flex", alignItems: "center", gap: 12 } as CSSProperties,
  hint: { flex: 1, fontSize: 12, color: "var(--text-muted)", margin: 0 } as CSSProperties,
  list: { display: "flex", flexDirection: "column", gap: 6 } as CSSProperties,
  empty: {
    border: "1px dashed var(--border)",
    borderRadius: 8,
    padding: "24px 16px",
    textAlign: "center",
  } as CSSProperties,
  emptyTitle: { fontSize: 14, fontWeight: 600, color: "var(--text-primary)", marginBottom: 6 } as CSSProperties,
  emptyBody: { fontSize: 13, color: "var(--text-muted)", marginBottom: 14 } as CSSProperties,
  row: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "10px 14px",
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-surface)",
  } as CSSProperties,
  dragging: { opacity: 0.6, boxShadow: "0 6px 16px rgba(0,0,0,.18)" } as CSSProperties,
  handle: {
    cursor: "grab",
    color: "var(--text-muted)",
    display: "flex",
    alignItems: "center",
  } as CSSProperties,
  path: { flex: 1, fontFamily: "var(--mono)", fontSize: 13, color: "var(--text-primary)" } as CSSProperties,
  overlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,.32)",
    zIndex: 40,
  } as CSSProperties,
  drawer: {
    position: "fixed",
    right: 0,
    top: 0,
    bottom: 0,
    width: 420,
    maxWidth: "100vw",
    background: "var(--bg-surface)",
    borderLeft: "1px solid var(--border)",
    display: "flex",
    flexDirection: "column",
    zIndex: 41,
  } as CSSProperties,
  drawerHeader: {
    padding: "16px 20px",
    borderBottom: "1px solid var(--border)",
    display: "flex",
    alignItems: "flex-start",
    gap: 12,
  } as CSSProperties,
  drawerTitleCol: { flex: 1, display: "flex", flexDirection: "column", gap: 4 } as CSSProperties,
  drawerTitle: { fontSize: 14, fontWeight: 600, color: "var(--text-primary)" } as CSSProperties,
  drawerSubtitle: { fontSize: 12, color: "var(--text-muted)" } as CSSProperties,
  searchWrap: { padding: "12px 20px", borderBottom: "1px solid var(--border)" } as CSSProperties,
  search: {
    width: "100%",
    height: 32,
    padding: "0 10px",
    background: "var(--bg-input)",
    border: "1px solid var(--border)",
    borderRadius: 6,
    color: "var(--text-primary)",
    fontSize: 13,
  } as CSSProperties,
  pickerList: {
    flex: 1,
    overflow: "auto",
    padding: "8px 12px",
    display: "flex",
    flexDirection: "column",
    gap: 6,
  } as CSSProperties,
  pickerEmpty: {
    padding: "24px 12px",
    textAlign: "center",
    color: "var(--text-muted)",
    fontSize: 13,
  } as CSSProperties,
  pickerRow: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "10px 12px",
    background: "transparent",
    border: "1px solid var(--border)",
    borderRadius: 6,
    cursor: "pointer",
    textAlign: "left",
    color: "var(--text-primary)",
  } as CSSProperties,
  pickerRowPath: { flex: 1, fontFamily: "var(--mono)", fontSize: 13 } as CSSProperties,
};
