import type { CSSProperties } from "react";

export const s = {
  card: {
    display: "flex",
    flexDirection: "column",
    gap: 14,
    padding: 16,
    border: "1px solid var(--border, #e5e7eb)",
    borderLeft: "4px solid var(--accent-risk, #f97316)",
    background: "var(--accent-risk-bg, rgba(249, 115, 22, 0.06))",
    borderRadius: 8,
  } satisfies CSSProperties,
  notReadyBox: {
    padding: 16,
    border: "1px solid var(--border, #e5e7eb)",
    borderRadius: 8,
    fontSize: 13,
    color: "var(--text-secondary, #6b7280)",
  } satisfies CSSProperties,
  refreshingBanner: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "6px 10px",
    borderRadius: 6,
    background: "var(--accent-risk-bg, rgba(249, 115, 22, 0.12))",
    border: "1px solid var(--accent-risk, #f97316)",
    color: "var(--accent-risk, #f97316)",
    fontSize: 12,
  } satisfies CSSProperties,
  what: {
    fontSize: 14,
    fontWeight: 600,
    lineHeight: 1.5,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  why: {
    fontSize: 13,
    lineHeight: 1.5,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  riskLevelRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  } satisfies CSSProperties,
  riskLevelBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: "3px 9px",
    borderRadius: 999,
    fontSize: 12,
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: "0.04em",
    background: "var(--bg-elevated)",
    border: "1px solid var(--border)",
  } satisfies CSSProperties,
  riskRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
  } satisfies CSSProperties,
  riskChip: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: "3px 9px",
    borderRadius: 999,
    background: "var(--bg-elevated)",
    border: "1px solid var(--border)",
    fontSize: 12,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  reviewFocusHeading: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    marginBottom: 8,
  } satisfies CSSProperties,
  reviewFocusList: {
    margin: 0,
    padding: 0,
    listStyle: "none",
    display: "flex",
    flexDirection: "column",
    gap: 8,
  } satisfies CSSProperties,
  reviewFocusItem: {
    listStyle: "none",
  } satisfies CSSProperties,
  reviewFocusLink: {
    display: "flex",
    alignItems: "flex-start",
    gap: 10,
    padding: "8px 10px",
    borderRadius: 6,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    textDecoration: "none",
    color: "inherit",
  } satisfies CSSProperties,
  reviewFocusRank: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    minWidth: 20,
    height: 20,
    borderRadius: 999,
    background: "var(--accent-risk, #f97316)",
    color: "#fff",
    fontSize: 11,
    fontWeight: 700,
    flexShrink: 0,
  } satisfies CSSProperties,
  reviewFocusBody: {
    display: "flex",
    flexDirection: "column",
    gap: 3,
    minWidth: 0,
  } satisfies CSSProperties,
  reviewFocusTitleRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  } satisfies CSSProperties,
  reviewFocusTitle: {
    fontSize: 13,
    fontWeight: 600,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  reviewFocusFileLine: {
    fontFamily: "var(--font-mono, monospace)",
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  reviewFocusNote: {
    fontSize: 12,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  footer: {
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  staleBanner: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    padding: "8px 12px",
    borderRadius: 6,
    background: "var(--warn-bg, #3a2a05)",
    border: "1px solid var(--warn, #d97706)",
    color: "var(--warn, #d97706)",
    fontSize: 13,
  } satisfies CSSProperties,
  progressLine: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 13,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  errorText: {
    fontSize: 13,
    color: "var(--crit, #dc2626)",
  } satisfies CSSProperties,
} as const;
